"""add project_id to issue

Revision ID: 4ebf4f1e7e95
Revises: 4d46f3fd2fe7
Create Date: 2026-04-29 14:30:02.945700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ebf4f1e7e95'
down_revision: Union[str, Sequence[str], None] = '4d46f3fd2fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
