"""add issue comment table

Revision ID: e5a5b8ed3ab0
Revises: 4ebf4f1e7e95
Create Date: 2026-04-29 16:03:23.378962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a5b8ed3ab0'
down_revision: Union[str, Sequence[str], None] = '4ebf4f1e7e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
